version: '3.1'

services:
    reverseproxy:
        image: nginx:stable-perl
        container_name: nginxrp
        volumes:
            - ./nginx/html:/var/www/html
            - ./web/src/portal:/var/www/portal/html
            - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
            - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ./nginx/conf/portal.conf:/etc/nginx/conf.d/portal.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - mysql
            
    mysql:
        image: mysql:latest
        container_name: mysql
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: "root123"
            MYSQL_DATABASE: "wordpress"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
