version: '3.1'

services:
    reverseproxy:
        image: nginx:stable-perl
        container_name: nginxrp
        volumes:
            - ./nginx/html:/var/www/html
            - ./web/src/portal:/var/www/portal/html
            - ./web/src/b2b:/var/www/b2b/html
            - ./nginx/conf/b2b.conf:/etc/nginx/conf.d/b2b.conf
            - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
            - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ./nginx/conf/portal.conf:/etc/nginx/conf.d/portal.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
            - mysql
        networks:
          - internal

    mysql:
        image: mysql:oracle
        hostname: mysql
        container_name: mysql
        restart: always
        volumes:
            - ./web/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./web/mysql/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: woodytoys
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
        ports:
            - "3306:3306"
        networks:
          - internal
    php:
        build:
          context: ./web/php
        hostname: php
        networks:
          - internal
        container_name: php
        volumes:
          - ./web/src/b2b:/var/www/b2b/html  
        restart: unless-stopped
        working_dir: /var/www/b2b/html
        expose:
          - 9000

networks:
  internal:
    driver: bridge
