version: '3'
services:
     nginx:
         image: nginx
         volumes:
          - ./web/src:/var/www/+
          - ./templates:/etc/nginx/templates
         ports:
          - "8080:80"
         environment:
          - NGINX_HOST=seldric.be
          - NGINX_PORT=80
