version: '3.1'

services:
    reverseproxy:
        image: nginx:stable-perl
        container_name: nginxrp
        volumes:
            - ./nginx/conf/core.conf:/etc/nginx/conf.d/core.conf
            - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf
            - ./nginx/conf/portal.conf:/etc/nginx/conf.d/portal.conf
            - ./nginx/html:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - wordpress
            - mysql
    
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        volumes:
            - ./web/src/portal:/var/www/html
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST="mysql"
            - WORDPRESS_DB_USER="admin"
            - WORDPRESS_DB_PASSWORD="admin"
            - WORDPRESS_DB_NAME="wordpress"
    mysql:
        image: mysql:lastest
        container_name: mysql
        volumes:
            - ./mysql/db:/var/lib/mysql
            - ./mysql/conf.d:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: "root123"
            MYSQL_DATABASE: "wordpress"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
